import Navbar from "@/components/Navbar";
import "./globals.css";
import QueryWrapper from "@/components/QueryWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-gray-800">
        <QueryWrapper>
          <header>
            <Navbar />
          </header>
          <main>{children}</main>
        </QueryWrapper>
      </body>
    </html>
  );
}
